name: WanderingTrades
author: jmp
version: ${project.version}
website: https://www.spigotmc.org/resources/wandering-trades.79068/
main: xyz.jpenilla.wanderingtrades.WanderingTrades
api-version: 1.14
description: Customizable Trades for Wandering Traders. Inspired by Vanilla Tweaks
softdepend: [McRPG, WorldEdit, WorldGuard, Vault, Prisma, PlaceholderAPI]
